# Rookery Bay R Training

[R](https://www.r-project.org/) is a language for statistical computing as well as a general purpose programming language. R has become one of the primary languages used in data science and for data analysis across many of the natural sciences. This training workshop will provide attendees with the foundations for continued learning of R and for analysis of a range of data types. 

## Course objectives

This course is designed to expose you to the fundamentals of using R for reproducible data analysis workflows.  A specific focus will be on using monitoring data from the [NERRS CDMO](https://cdmo.baruch.sc.edu/) for novel analyses and storytelling to increase the impact of these valuable sources of information. You will not be experts by the end of the course, but you will have a solid foundation for continued learning.  By the end of this course you will be able to or have the resources to find out how to:

* Use R to import and organize data
* Create plots using R packages for exploratory data analysis
* Use R to work with CDMO SWMP data

## Agenda

Training will occur remotely on Monday __June 29th__ and Tuesday __June 30th__, login information will be sent by email. 

__Day 1, June 29th: __


* __1:00 - 2:00__ The what, why, and how of R
  
  BREAK
  
* __2:15 - 3:15__ Importing and wrangling data with the tidyverse
  
  BREAK
  
* __3:30 - 4:30__ Plotting data with ggplot2

__Day 2, June 30th:__

* __1:00 - 2:00__ Importing and wrangling CDMO SWMP data into R
  
  BREAK
  
* __2:15 - 3:15__ Analyzing CDMO SWMP data in R
  
  BREAK
  
* __3:30 - 4:30__ Spatial data analysis with simple features

## Software requirements

Please make sure you have the required software installed on your computer, specifically [RStudio](https://rstudio.com/products/rstudio/download/) and [R](https://mirrors.nics.utk.edu/cran/). The [setup instructions](setup.html) will guide you through the installation process.  Take note of the required R packages that you must also download and install.  Please contact the instructor with any questions or issues related to setup.  

## Instructor

[Marcus Beck](https://fawda123.github.io/CV/Beck_CV.pdf) ([mbeck@tbep.org](mailto:mbeck@tbep.org)) - Marcus is the Program Scientist for the Tampa Bay Estuary Program and is developing data analysis and visualization methods for Bay health indicators.  He received his BS in Zoology from the University of Florida in 2007 and his MSc and PhD in Conservation Biology from the University of Minnesota in 2009 and 2013. Marcus has experience researching environmental indicators and developing open science products to support environmental decision-making.  He has over ten years of experience using and developing software in the R Statistical Programming Language and is the lead developer for the [SWMPr](https://journal.r-project.org/archive/2016/RJ-2016-015/index.html) R package to retrieve, organize, and analyze NERRS data from the SWMP network.

## Source content

All source materials for this website can be accessed at https://github.com/tbep-tech/rookery-bay-training
